XReport/Controllers/ExcelHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
//using OfficeOpenXml;
using Microsoft.Office.Interop.Excel;
using System.Data;
using System.Runtime.InteropServices;
using GridMvc;
using System.Collections;
using System.Diagnostics;


namespace XReport.Controllers
{
    public class ExcelHomeController : Controller
    {
       public static string csvFilePath, xlsFilePath, excelFilePath = string.Empty;
      
        // GET: ExcelHome
        public ActionResult UploadExcel()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadExcel(HttpPostedFileBase file)
        {

            if (Request.Files["file"].ContentLength > 0)
            {
                string fileExtension = System.IO.Path.GetExtension(Request.Files["file"].FileName);
               
               
                if (fileExtension == ".csv")
                {
                    csvFilePath =    System.IO.Path.GetFullPath(Request.Files["file"].FileName);
                    excelFilePath = @"D:\" + (Path.GetFileName(Request.Files["file"].FileName)).Replace(fileExtension, ".xlsx");

                   Application app = new Application();
                   Workbook wb = app.Workbooks.Open(csvFilePath, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing);
                   wb.SaveAs(excelFilePath, XlFileFormat.xlOpenXMLWorkbook, Type.Missing, Type.Missing, Type.Missing, Type.Missing, XlSaveAsAccessMode.xlExclusive, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing);
                   wb.Close();
                   Marshal.ReleaseComObject(wb);
                   app.Quit();

                   Marshal.ReleaseComObject(app);
                   KillExcel();
                   ViewBag.data = "Converted from .csv to .xslx !! find at " + excelFilePath;
                   ViewBag.Status = "Yes";
                   return View();
                  
                }

                else if (fileExtension == ".xls" || fileExtension == ".xlsx" )
                {
                    if (fileExtension == ".xls")
                    {
                        xlsFilePath = System.IO.Path.GetFullPath(Request.Files["file"].FileName);
                        excelFilePath = @"D:\" + (Path.GetFileName(Request.Files["file"].FileName)).Replace(fileExtension, ".xlsx");
                        Application app = new Application();
                        Workbook wb = app.Workbooks.Open(xlsFilePath, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing);
                       
                        wb.SaveAs(excelFilePath, XlFileFormat.xlOpenXMLWorkbook, Type.Missing, Type.Missing, Type.Missing, Type.Missing, XlSaveAsAccessMode.xlExclusive, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing);
                       

                        ViewBag.data = "Converted from .xls to .xlsx !! find at " + excelFilePath;
                        ViewBag.Status = "Yes";
                        wb.Close();
                        Marshal.ReleaseComObject(wb);
                        app.Quit();
                       
                        Marshal.ReleaseComObject(app);
                        KillExcel();
                        return View();

                    }
                   
                }
                else
                ViewBag.Data = "some error,make sure you are uploading a .xls or .xlsx format file only";
                ViewBag.Status = "No";
            }
                              
            return View();
           
        }

        public void KillExcel()
        {
           var process = System.Diagnostics.Process.GetProcessesByName("Excel");
           foreach (var p in process)
           {
               if (!string.IsNullOrEmpty(p.ProcessName))
               {
                   try
                   {
                       p.Kill();
                   }
                   catch { }
               }
           }

        }
 
        [HttpGet]
       /* public ActionResult GenerateReport()
        {
           
                Application xlApp = new Application();
                Workbook xlWorkbook = xlApp.Workbooks.Open(excelFilePath);
                _Worksheet xlWorksheet = xlWorkbook.Sheets[1];
                Range xlRange = xlWorksheet.UsedRange;

                int rowCount = xlRange.Rows.Count;
                int colCount = xlRange.Columns.Count;
                int MaincolCount = xlRange.Columns.Count;

                System.Data.DataTable tableReport = new System.Data.DataTable();


                int suf = 0;
                try
                {

                    for (int i = 1; i <= rowCount; i++)
                    {

                        colCount = MaincolCount;
                        if (colCount!=0)
                        { 
                       // colCount = MaincolCount;
                        foreach (object columnName in xlRange.Rows[i].Value)
                        {
                            string temp = Convert.ToString(columnName);
                           
                                if (!tableReport.Columns.Contains(temp))
                                {
                                    tableReport.Columns.Add(temp);
                                }
                                else
                                {
                                    tableReport.Columns.Add(temp + suf);
                                    suf++;
                                }

                                colCount = colCount - 1;

                                                     
                        }
                        }
                        else 
                        {
                            if (i == 1)
                                break;
                                else
                            { 
                               DataRow row = tableReport.NewRow();
                            row["id"] = i;
                            row["item"] = "item " + i.ToString();
                            tableReport.Rows.Add(row);
                               // tableReport.Rows.Add(xlRange.Rows[i].Value);
                            }
                        }
                       
                    }

                    Session["table"] = tableReport;
            }
            finally
                {
          
            Marshal.ReleaseComObject(xlRange);
           Marshal.ReleaseComObject(xlWorksheet);
           xlWorkbook.Close();
           Marshal.ReleaseComObject(xlWorkbook);
            xlApp.Quit();
           Marshal.ReleaseComObject(xlApp);
                }
               Response.Redirect("http://localhost:64761/Report.aspx");
                return View(tableReport);

        }*/

        private List<IDictionary> ConvertToDictionary(System.Data.DataTable dtObject)
        {
            var columns = dtObject.Columns.Cast<DataColumn>();

            var dictionaryList = dtObject.AsEnumerable()
                .Select(dataRow => columns
                    .Select(column =>
                        new { Column = column.ColumnName, Value = dataRow[column] })
                             .ToDictionary(data => data.Column, data => data.Value)).ToList().ToArray();

            return dictionaryList.ToList<IDictionary>();
        }
 
        public ActionResult GenerateReport()
        {

            Application xlApp = new Application();
            Workbook xlWorkbook = xlApp.Workbooks.Open(excelFilePath);
            _Worksheet xlWorksheet = xlWorkbook.Sheets[1];
            Range xlRange = xlWorksheet.UsedRange;

            int rowCount = xlRange.Rows.Count;
            int colCount = xlRange.Columns.Count;
            int MaincolCount = xlRange.Columns.Count;
            string[] columnsofTable = new string[colCount];
            System.Data.DataTable tableReport = new System.Data.DataTable();
            DataRow row;
         
           
            int suf = 0;
            int r=0;
            string cl=string.Empty;
            try
            {
                for (int i = 1; i <= rowCount; i++)
                {
                  
                    row = tableReport.NewRow();
                    colCount = MaincolCount;

                    foreach (object value1  in xlRange.Rows[i].Value)
                    {
                        string temp = Convert.ToString(value1);

                        if (i == 1)
                        { 
                                 if (colCount != 0 )
                                {
                                        if (!tableReport.Columns.Contains(temp))
                                        {
                                            if(temp.Contains("Date"))
                                            {
                                                tableReport.Columns.Add(temp, typeof(DateTime));
                                                columnsofTable[colCount - 1] = temp;
                                            }
                                            else
                                            { 
                                            tableReport.Columns.Add(temp);
                                            columnsofTable[colCount-1] = temp;
                                            }
                                        }
                                        else
                                        {
                                            cl = temp + suf;
                                            tableReport.Columns.Add(cl);

XReport/Views/ExcelHome/CreateReport.cshtml
@using System.Dynamic
@model List<System.Collections.IDictionary>
@{
    var result = new List<dynamic>();

    foreach (var emprow in Model)
    {
        var row = (IDictionary<string, object>)new ExpandoObject();
        Dictionary<string, object> eachEmpRow = (Dictionary<string, object>)emprow;

        foreach (KeyValuePair<string, object> keyValuePair in eachEmpRow)
        {
            row.Add(keyValuePair);
        }
        result.Add(row);
    }
    var grid = new WebGrid(result);
}

@if (@Model != null)
{
    @grid.GetHtml(tableStyle: "grid", headerStyle: "head", alternatingRowStyle: "alt");
}

XReport/Views/ExcelHome/GenerateReport.cshtml
@using System.Dynamic
@model List<System.Collections.IDictionary>
@{
    var result = new List<dynamic>();

    foreach (var emprow in Model)
    {
        var row = (IDictionary<string, object>)new ExpandoObject();
        Dictionary<string, object> eachEmpRow = (Dictionary<string, object>)emprow;

        foreach (KeyValuePair<string, object> keyValuePair in eachEmpRow)
        {
            row.Add(keyValuePair);
        }
        result.Add(row);
    }
    var grid = new WebGrid(result);
}

@if (@Model != null)
{
    @grid.GetHtml(tableStyle: "grid", headerStyle: "head", alternatingRowStyle: "alt");
}

XReport/Views/ExcelHome/UploadExcel.cshtml
@{
    ViewBag.Title = "Upload Excel";
    Layout = "~/Views/Shared/_ExcelLayout.cshtml";
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
}


@using (Html.BeginForm("UploadExcel", "ExcelHome", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 

<div class="jumbotron" style="background-color:lightblue">
    <div class=" container">
        <div class="row">
            <div class="panel">
                <div class="panel-heading">
                    <div class="col"><span class="h3">Please upload excel sheet here</span></div>                   
                </div>
                <div class="panel-body">
                    <input style="height:40px" id="File1" type="file" name="file" />
                </div>
                
                <span style="color:green">@ViewBag.Data</span></div>
              <br />
                
                @if (ViewBag.panel == "Visible")
                {
                    <button type="button" class="btn btn-md btn-danger" onclick="location.href ='@Url.Action("ViewReport", "ExcelHome")'" > View Data </button>
                }
                
                <br />
                <br />
            </div>
            
          
        <input class="btn-success btn-lg" type="submit" style="width:220px" value="Submit" id="submit"/> <span>&nbsp;&nbsp; </span>

            @if (ViewBag.Status == "Yes")
            {
                
     <span  style="color:green" class="h2 glyphicon glyphicon-arrow-right">&nbsp;&nbsp; </span>
    <button id="btnReportGen" type="button" class="btn btn-lg btn-success" style="width:220px" onclick="location.href ='@Url.Action("GenerateReport", "ExcelHome")'"> Generate Report </button>
    <span > &nbsp;&nbsp; </span>
            }
            @if (ViewBag.Status == "No")
            {
                <input class="btn-danger btn-lg" type="button" onclick="" value="Generate Report" style="display: none" />
            }
            @if (ViewBag.panel == "Visible")
            {
                
                <span style="color:green" class="h2 glyphicon glyphicon-arrow-right"> &nbsp;&nbsp; </span>
                <button style="width:220px" type="button" class="btn btn-lg btn-success" onclick="location.href ='@Url.Action("CreateReport", "ExcelHome")'"> Create </button>

            }
            @if (ViewBag.panel == "Visible")
            {
            }

        </div>
    </div>

}